### ISSUE TITLE
Error building eva-owyl docker

### ISSUE THREAD

**Issue by amitpdev** [opencog/docker#111]
Hi, I'm getting the following error when building eva-owyl docker image. Tried on two different computers. same failure:

> Step 30 : RUN bash -l -c "/opt/ros/indigo/bin/catkin_make"
 ---> Running in 7f15c0827390
CMake Error at CMakeLists.txt:20 (message):
  Search for 'catkin' in workspace failed (catkin_find_pkg catkin
  /catkin_ws/src): Traceback (most recent call last):
>
>    File "/usr/local/bin/catkin_find_pkg", line 33, in <module>
      main()
    File "/usr/local/bin/catkin_find_pkg", line 21, in main
      packages = find_packages(args.base_path)
    File "/usr/local/lib/python3.4/dist-packages/catkin_pkg/packages.py", line 83, in find_packages
      packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces)
    File "/usr/local/lib/python3.4/dist-packages/catkin_pkg/packages.py", line 109, in find_packages_allowing_duplicates
      packages[path] = parse_package(os.path.join(basepath, path))
    File "/usr/local/lib/python3.4/dist-packages/catkin_pkg/package.py", line 356, in parse_package
      return parse_package_string(f.read(), filename)
    File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
>
>  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 273:
  ordinal not in range(128)
>
>
>-- Configuring incomplete, errors occurred!
See also "/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
Base path: /catkin_ws
Source space: /catkin_ws/src
Build space: /catkin_ws/build
Devel space: /catkin_ws/devel
Install space: /catkin_ws/install
\####
\#### Running command: "make cmake_check_build_system" in "/catkin_ws/build"
\####
The command '/bin/sh -c bash -l -c "/opt/ros/indigo/bin/catkin_make"' returned a non-zero code: 1

**Comment by AmeBel** [comment]
stail
