### ISSUE TITLE
pull access denied for opencog/jupyter

### ISSUE THREAD

**Issue by austineinstein** [opencog/docker#135]
Hi,

Please in trying to run jupyter kernels with opencog. I find that the notebooks directory does not exist   -> $OPENCOG_NOTEBOOKS:/opencog/notebooks

So I get this errors in trying to pull 
<img width="1237" alt="screen shot 2018-08-04 at 04 24 01" src="https://user-images.githubusercontent.com/12557036/43672259-2353ecb4-97a2-11e8-898f-b73b7d6d5ccb.png">

<img width="691" alt="screen shot 2018-08-04 at 04 29 37" src="https://user-images.githubusercontent.com/12557036/43672262-35f36eb2-97a2-11e8-8b63-706191e5d12f.png">

**Comment by Eskender-B** [comment]
Did you follow all the steps outlined [here](https://github.com/opencog/docker/tree/master/opencog#steps-for-running-jupyter-kernels-with-opencog)

 * clone repo
 * cd into opencog directory
 * Then you need to build the docker images via `./docker-build -j`
 * Setup notebooks save directory `export OPENCOG_NOTEBOOKS=$HOME/path/to/opencog_notebooks`

All the steps are listed in the readme link provided above.

**Comment by Eskender-B** [comment]
Before building jupyter image via `./docker-build -j`, you may need to build opencog images first via `./docker-build -a`. Jupyter image depends on opencog image.

**Comment by austineinstein** [comment]
Rebuilding by running ./docker-build -j and adding this path export OPENCOG_NOTEBOOKS=$HOME/path/to/opencog/tools/jupyter_notebook fixed it.
Thanks!
