### ISSUE TITLE
can't build relex

### ISSUE THREAD

**Issue by noskill** [opencog/docker#136]
running ./docker-build.sh -r gives an error.
I'll try build image with maven instead of ant

> 
> relex-master/src/resources/logback.xml
> relex-master/test-corpus.txt
> Buildfile: /home/Downloads/relex-master/build.xml
> 
> build-subprojects:
> 
> init:
> 
> build-version:
>      [echo] Building RelEx version 1.6.3
>      [copy] Copying 1 file to /home/Downloads/relex-master/src/java/relex
> 
> look-for-owl:
>      [echo] Will not build (optional) OWL output format; org.semanticweb.owl classes not found.
> 
> look-for-opennlp:
> 
> build-project:
>      [echo] relex: /home/Downloads/relex-master/build.xml
>     [mkdir] Created dir: /home/Downloads/relex-master/bin
>     [javac] Compiling 79 source files to /home/Downloads/relex-master/bin
>     [javac] /home/Downloads/relex-master/src/java/relex/RelationExtractor.java:30: error: package org.slf4j does not exist
>     [javac] import org.slf4j.Logger;
>     [javac]                 ^
>     [javac] /home/Downloads/relex-master/src/java/relex/RelationExtractor.java:31: error: package org.slf4j does not exist
>     [javac] import org.slf4j.LoggerFactory;
>     [javac]                 ^
>     [javac] /home/Downloads/relex-master/src/java/relex/RelationExtractor.java:69: error: cannot find symbol
>     [javac] 	private static final Logger logger = LoggerFactory.getLogger(RelationExtractor.class);
>     [javac] 	                     ^
>     [javac]   symbol:   class Logger
>     [javac]   location: class RelationExtractor
>     [javac] /home/Downloads/relex-master/src/java/relex/algs/AlgorithmApplier.java:19: error: package org.slf4j does not exist
>     [javac] import org.slf4j.Logger;
>     [javac]                 ^
>     [javac] /home/Downloads/relex-master/src/java/relex/algs/AlgorithmApplier.java:20: error: package org.slf4j does not exist
>     [javac] import org.slf4j.LoggerFactory;
>     [javac]                 ^
>     [javac] /home/Downloads/relex-master/src/java/relex/utils/ResourceUtils.java:3: error: package org.slf4j does not exist
>     [javac] import org.slf4j.Logger;
>     [javac]                 ^
>     [javac] /home/Downloads/relex-master/src/java/relex/utils/ResourceUtils.java:4: error: package org.slf4j does not exist
>     [javac] import org.slf4j.LoggerFactory;
>     [javac]                 ^
>     [javac] /home/Downloads/relex-master/src/java/relex/algs/AlgorithmApplier.java:38: error: cannot find symbol
>     [javac] 	private static final Logger logger = LoggerFactory.getLogger(AlgorithmApplier.class);
>     [javac] 	                     ^
>     [javac]   symbol:   class Logger
>     [javac]   location: class AlgorithmApplier
>     [javac] /home/Downloads/relex-master/src/java/relex/algs/SentenceAlgorithm.java:25: error: package org.slf4j does not exist
>     [javac] import org.slf4j.Logger;
>     [javac]                 ^
>     [javac] /home/Downloads/relex-master/src/java/relex/algs/SentenceAlgorithm.java:26: error: package org.slf4j does not exist
>     [javac] import org.slf4j.LoggerFactory;
>     [javac]                 ^
>     [javac] /home/Downloads/relex-master/src/java/relex/utils/ResourceUtils.java:14: error: cannot find symbol
>     [javac]     private static final Logger logger = LoggerFactory.getLogger(ResourceUtils.class);
>     [javac]                          ^
>     [javac]   symbol:   class Logger
>     [javac]   location: class ResourceUtils
>     [javac] /home/Downloads/relex-master/src/java/relex/algs/SentenceAlgorithm.java:33: error: cannot find symbol
>     [javac] 	private static final Logger logger = LoggerFactory.getLogger(SentenceAlgorithm.class);
>     [javac] 	                     ^
>     [javac]   symbol:   class Logger
>     [javac]   location: class SentenceAlgorithm
>     [javac] /home/Downloads/relex-master/src/java/relex/parser/LocalLGParser.java:26: error: package org.slf4j does not exist
>     [javac] import org.slf4j.Logger;
>     [javac]                 ^
>     [javac] /home/Downloads/relex-master/src/java/relex/parser/LocalLGParser.java:27: error: package org.slf4j does not exist
>     [javac] import org.slf4j.LoggerFactory;
>     [javac]                 ^
>     [javac] /home/Downloads/relex-master/src/java/relex/parser/LocalLGParser.java:37: error: cannot find symbol
>     [javac] 	private static final Logger logger = LoggerFactory.getLogger(LocalLGParser.class);
>     [javac] 	                     ^
>     [javac]   symbol:   class Logger
>     [javac]   location: class LocalLGParser
>     [javac] /home/Downloads/relex-master/src/java/relex/RelationExtractor.java:69: error: cannot find symbol
>     [javac] 	private static final Logger logger = LoggerFactory.getLogger(RelationExtractor.class);
>     [javac] 	                                     ^
>     [javac]   symbol:   variable LoggerFactory
>     [javac]   location: class RelationExtractor
>     [javac] /home/Downloads/relex-master/src/java/relex/utils/ResourceUtils.java:14: error: cannot find symbol
>     [javac]     private static final Logger logger = LoggerFactory.getLogger(ResourceUtils.class);
>     [javac]                                          ^
>     [javac]   symbol:   variable LoggerFactory
>     [javac]   location: class ResourceUtils
>     [javac] /home/Downloads/relex-master/src/java/relex/algs/AlgorithmApplier.java:38: error: cannot find symbol
>     [javac] 	private static final Logger logger = LoggerFactory.getLogger(AlgorithmApplier.class);
>     [javac] 	                                     ^
>     [javac]   symbol:   variable LoggerFactory
>     [javac]   location: class AlgorithmApplier
>     [javac] /home/Downloads/relex-master/src/java/relex/algs/SentenceAlgorithm.java:33: error: cannot find symbol
>     [javac] 	private static final Logger logger = LoggerFactory.getLogger(SentenceAlgorithm.class);
>     [javac] 	                                     ^
>     [javac]   symbol:   variable LoggerFactory
>     [javac]   location: class SentenceAlgorithm
>     [javac] /home/Downloads/relex-master/src/java/relex/parser/LocalLGParser.java:37: error: cannot find symbol
>     [javac] 	private static final Logger logger = LoggerFactory.getLogger(LocalLGParser.class);
>     [javac] 	                                     ^
>     [javac]   symbol:   variable LoggerFactory
>     [javac]   location: class LocalLGParser
>     [javac] 20 errors
> 

> BUILD FAILED
> /home/Downloads/relex-master/build.xml:95: Compile failed; see the compiler error output for details.
> 
> Total time: 0 seconds
> The command '/bin/sh -c tar -xvf master.tar.gz; cd relex-master; ant' returned a non-zero code: 1

**Comment by noskill** [comment]
need to upgrade dependency for relex https://github.com/opencog/relex/pull/277

**Comment by linas** [comment]
Ant assumes that the dependencies are already installed. I thought that the docker image installed all the required dependencies.  Maven is just a different way to build.

**Comment by noskill** [comment]
fixed by https://github.com/opencog/docker/pull/137
