### ISSUE TITLE
add working sql backing store to docker file

### ISSUE THREAD

**Issue by mjsduncan** [opencog/docker#142]
now that the agi-bio project is starting experiments with large atomspaces, it would be great if a working postgresql atomspace database could be installed & configured in the Dockerfile image.  i've been unable to get it to work in the current container through the cogserver or in the unit tests, despite repeatedly following, checking & rechecing the multiple README files.  the test databases exist and are accessable with the users given in the respective config files.  proper permissions are emphasized but not stated explicitly:  what should they be?  the only other clue i've come up with is that for the current build "docker ps" lists the port mapping as "0.0.0.0:17001->17001/tcp; 0.0.0.0:18001->18001/tcp" while /etc/hosts has the usual "127.0.0.1  localhost".  any suggestions?

thanks,
mike

**Comment by AmeBel** [comment]
stail
