### ISSUE TITLE
Change name to opencog-docker-containers

### ISSUE THREAD

**Issue by jdddog** [opencog/docker#15]
I think we should change the name of this to something like opencog-docker-containers so that people don't confuse it with ros and because its a more accurate description of what this repository contains.

**Comment by linas** [comment]
David, I'd like to change the name too: I have a student who will be creating docker files for opencog NLP stuff, and it would be nice to have a place to put those.

... unless we should be putting docker files directly into the opencog repo?  So that my nlp ones would be in /opencog/nlp/docker ?

**Comment by githart** [comment]
Putting Dockerfiles directly into the OpenCog repo is most sensibe, IMO. 

A name change of this repo is okay by me too.

**Comment by AmeBel** [comment]
@linas it would be great if this would be renamed and the docker directory from https://github.com/opencog/opencog/tree/master/docker extracted to here. That way different configurations can be setup and made to autobuild @ https://registry.hub.docker.com/repos/opencog/

**Comment by linas** [comment]
@AmeBel I just renamed it to "docker" viz its now https://github.com/opencog/docker  Do as you will ...
