### ISSUE TITLE
problem with /etc/localtime with docker on Mac

### ISSUE THREAD

**Issue by luketpeterson** [opencog/docker#151]
Following the instructions in the ReadMe, the opencog container won't start.  The problem is the way the MacOS virtualizes the /etc/ filesystem, and the way the OpenCog container maps /etc/localtime

This issue affects many containers, and is not OpenCog specific.  Nonetheless the recommended work-around is a change to the container.

See this thread.  [https://github.com/docker/for-mac/issues/2396]

The solution I implemented is from the commend by the user: “smlng” on Dec 19, 2018

**Config Details**
Mac OS 10.15.6
docker engine 19.03.12

**Proposed Change**
I changed the docker/opencog/common.yml file

```
diff --git a/opencog/common.yml b/opencog/common.yml
index 0b6e758..0b12426 100644
--- a/opencog/common.yml
+++ b/opencog/common.yml
@@ -13,7 +13,7 @@ workspace:
     volumes:
         - $OPENCOG_SOURCE_DIR:/opencog
         - $HOME/.gitconfig:/home/opencog/.gitconfig # for git commits,stash ...
-        - /etc/localtime:/etc/localtime:ro # for syncing with host time.
+        - ${ETC_LOCALTIME}:/etc/localtime:ro # for syncing with host time.
         - $CCACHE_DIR:/home/opencog/.ccache # for persisting ccache artifacts
     environment: # Set environment variables within the container
         - OPENCOG_SOURCE_DIR=/opencog
```

And then set the environment variable along with all the others from the ReadMe.

So, my .zshenv (or .bashrc for those who use bash) now specifies:

```
#OpenCog envs 
export ETC_LOCALTIME=$(readlink /etc/localtime)
export CCACHE_DIR=$HOME/OpenCog/ccache_output
export OPENCOG_SOURCE_DIR=$HOME/OpenCog/opencog
export ATOMSPACE_SOURCE_DIR=$HOME/OpenCog/atomspace
export COGUTIL_SOURCE_DIR=$HOME/OpenCog/cogutil
export OC2MC_SOURCE_DIR=$HOME/OpenCog/opencog-to-minecraft
```

**Comment by linas** [comment]
Closing; fixed in pull req #162
