### ISSUE TITLE
Telnet fail

### ISSUE THREAD

**Issue by elymatos** [opencog/docker#157]
Hi!
I've pulled the images using 
`./docker-build.sh -a`
and start the containers via docker-compose using
`docker-compose run --service-ports dev`
but telnet is failing for port 17001 (and others too). I guess the server is not running, but I can't get how to start the server (is it is the case). Reference pointed at readme (run cogserver) is not working.
Thanks for help,
Ely

**Comment by linas** [comment]
The docker images are5+ years out of date and are no longer maintained. Fixing them is probably not hard, but no one uses them.

Which instructions pointed you here?

**Comment by elymatos** [comment]
Hi! Thanks for answer.
From the main page

[https://wiki.opencog.org/w/The_Open_Cognition_Project](https://wiki.opencog.org/w/The_Open_Cognition_Project)

section Activities has a link to "Building OpenCog"

[https://wiki.opencog.org/w/Building_OpenCog](https://wiki.opencog.org/w/Building_OpenCog)

From that, in section Containers there is as link to

[https://github.com/opencog/docker/blob/master/opencog/README.md](https://github.com/opencog/docker/blob/master/opencog/README.md)

Then I've tried to follow the instructions on readme.

My main objective at this point to learn about OpenCog is related to Natural Language Understanding/Processing. I'm working at FrameNet Brasil Project; we are using Frame Semantics, Generative Lexicon, Construction Grammar, Universal Dependencies, etc (somewhat associated to Cognitive Linguistics) and I'm very attracted by how AtomSpace/PLN can help on our projects. I saw the main implementation for NLP at OpenCog is using Link Grammar/RelEx and I want to investigate if it is possible to use (or adapt) to other syntactic/semantic theories.

If the Docker containers is not being used, what are the currently valid instructions to build OpenCog? Just build directly on a Ubuntu server?

Thanks once more,
Ely

**Comment by linas** [comment]
Hi Ely,
Several remarks:

first -- I was wrong about the docker containers being unmaintained; I looked at the history, and it does look like there somewhat regular updates. So, yes, it should have worked, I don't know why it doesn't.

second -- and more important -- the opencog server shell will not give you access either to link-grammar or to relex. So lets talk about link-grammar first. If you run Linux, say debian or ubuntu, it comes with the system, and you can install it as a regular package.  It might be half a year out of date, but for evaluation purposes, even production, you won't be missing anything.  For Apple, I think there is a Macports package.  For windows, you'd have to compile from source, which should work easily, but if not, it is supported on the link-grammar mailing list  (which is also a good place to ask questions.) See http://www.abiword.org/projects/link-grammar/

If you still want a docker container, link grammar does have one: here: https://github.com/opencog/link-grammar/tree/master/docker I haven't tried it in seven years, but .. who knows. It might work.

About relex, next comment.

**Comment by linas** [comment]
About relex: The source is here: https://github.com/opencog/relex/ -- its java, and thus, in principle "easy to build" on any OS. There are docker containers in a subdirectory; I see they are five years old, I don't know if they work or not.  

Relex documentation is here:  http://opencog.org/wiki/RelEx 

I would like to tell you several relex-related stories, but this is not the place. Perhaps you could join the link-grammar mailing list?

As to natural language, one of my primary projects is to automate the learning of grammar from raw text corpora ... but again, this is another conversation.

**Comment by elymatos** [comment]
Actually I've already tested relex container alone and it appears to be working as expected (although I still need to learn what is 'expected', rs).
I've have joint to google group for link-grammar list. I'll put my questions there.
Thanks!
Ely

**Comment by elymatos** [comment]
But...The question about how to start the server using the container is still open :-) :-)

**Comment by linas** [comment]
> The question about how to start the server using the container is still open :-) :-)

Yes, this is true. ... except that most of what's in there has been gutted, and there's nothing particularly interesting you can do with the server, alone. You'd have to go to the individual projects, e.g. https://github.com/opencog/learn to get the language stuff.

The server at 17001 is, at this point, just a shell server, allowing you to use multiple scheme and/or python terminals all accessing the same AtomSpace. It's nothing more than that. The AtomSpace is a metagraph database; a kind-of foundation for everything in opencog. See https://github.com/opencog/atomspace -- It has python and scheme interfaces, which you can access directly from the python shell or the scheme shell.  The cogserver, the telnet at 17001, just gives you additional terminals into that. e.g. you can manipulate the same data with either scheme, or with python, at the same time! So that's pretty cool!  https://github.com/opencog/cogserver ... but, without data to manipulate, its kind of useless. Again, it doesn't provide interesting access to anything that you haven't set up independently, and the docker container is not setting up any of the interesting things.

**Comment by elymatos** [comment]
I'll consider that! The "learn" repository seems to be more related to what I'm looking for. Is there some discussion list about this theme as it has to link-grammar?
Thanks,
Ely

**Comment by linas** [comment]
> Is there some discussion list about this?

I cross-post to both link-grammar, and to the general opencog mailing list, as it concerns both. Post publicly on one or the other or both, or write privately.

**Comment by linas** [comment]
I think pull req #158 will fix the original issue.

**Comment by linas** [comment]
Closing, #158 fixes it.
