### ISSUE TITLE
Error building indigo/ros-opencog docker

### ISSUE THREAD

**Issue by Mforrest20** [opencog/docker#173]
This issue varies depending on the version of OpenCog files it's told to use. This issue is based on setting the date to 2017-07-01.

I've made some changes to get this image to build up to this point and these changes can be seen in https://github.com/Mforrest20/opencog-docker under branch MF/indigo-tinker. In any case here's the error that is eventually spit out after running the .build.sh file for the ros-opencog dockerfile.

I was looking at using the noetic build since its a newer ROS version. It doesn't seem like you've had much part in getting that working, but if I should work towards goal of running eva with opencog in that ROS version let me know and I'll close this issue and open one related to that. (It fails around a similar spot)

```
[ 89%] Compiling opencog/exec.scm
Backtrace:
In system/base/compile.scm:
    59:11 19 (_)
   155:11 18 (_ #<closed: file 1b6c690>)
   235:18 17 (read-and-compile #<input: opencog/exec.scm 13> #:from _ …)
   183:32 16 (compile-fold (#<procedure compile-tree-il (x e opts)>) …)
In ice-9/boot-9.scm:
   2312:4 15 (save-module-excursion #<procedure 19ef2c0 at language/…>)
In language/scheme/compile-tree-il.scm:
    31:15 14 (_)
In ice-9/psyntax.scm:
  1235:36 13 (expand-top-sequence ((use-modules (opencog))) _ _ #f c …)
  1182:24 12 (parse _ (("placeholder" placeholder)) ((top) #(# # …)) …)
   285:10 11 (parse _ (("placeholder" placeholder)) (()) _ c&e (# #) #)
In ice-9/boot-9.scm:
  3365:20 10 (process-use-modules _)
   222:17  9 (map1 (((opencog))))
  3366:31  8 (_ ((opencog)))
  2788:17  7 (resolve-interface (opencog) #:select _ #:hide _ # _ # _ …)
  2714:10  6 (_ (opencog) _ _ #:ensure _)
  2982:16  5 (try-module-autoload _ _)
   2312:4  4 (save-module-excursion #<procedure 1b3f9f0 at ice-9/boo…>)
  3002:22  3 (_)
In unknown file:
           2 (primitive-load-path "opencog" #<procedure 19fb380 at i…>)
           1 (load-extension "EXT_LIB_PATH-NOTFOUND/libsmob" "openco…")
In ice-9/boot-9.scm:
   752:25  0 (dispatch-exception _ _ _)

ice-9/boot-9.scm:752:25: In procedure dispatch-exception:
In procedure dynamic-link: file: "EXT_LIB_PATH-NOTFOUND/libsmob", message: "file not found"
make[2]: *** [opencog/scm/opencog/exec.go] Error 1
make[1]: *** [opencog/scm/CMakeFiles/opencog_exec_go.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 89%] Building CXX object opencog/persist/sql/multi-driver/CMakeFiles/persist-sql.dir/SQLUUID.cc.o
[ 92%] Building CXX object opencog/persist/sql/multi-driver/CMakeFiles/persist-sql.dir/SQLPersistSCM.cc.o
Linking CXX shared library libpersist-sql.so
[ 92%] Built target persist-sql
make: *** [all] Error 2
[  0%] Built target SCM_CONFIG
[  2%] Built target opencog_atom_types
[  2%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__opencog_atomspace_opencog_atoms_atom_types
[  5%] Built target atom_types
[ 12%] Built target value
[ 15%] Built target truthvalue
[ 17%] Built target atombase
[ 35%] Built target atomcore
[ 38%] Built target atomflow
[ 41%] Built target parallel
[ 48%] Built target clearbox
[ 51%] Built target execution
[ 51%] Built target foreign
[ 53%] Built target grounded
[ 53%] Built target join
[ 58%] Built target query-engine
[ 64%] Built target pattern
[ 66%] Built target atomspace
[ 66%] Built target storage_types
[ 66%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__opencog_atomspace_opencog_persist_storage
[ 66%] Built target storage-types
[ 71%] Built target smob
[ 74%] Built target persist
[ 76%] Built target sexpr
[ 76%] Built target load_scm
[ 76%] Built target persist-file
[ 79%] Built target json
[ 79%] Built target persist-pg
[ 82%] Built target tlb
[ 89%] Built target persist-sql
Scanning dependencies of target sniff
[ 92%] Building CXX object opencog/persist/sql/multi-driver/CMakeFiles/sniff.dir/sniff.cc.o
Linking CXX executable sniff
[ 92%] Built target sniff
[ 92%] Built target exec
[ 94%] Built target guile-uuid
[ 94%] Built target logger
[ 94%] Built target randgen
[ 94%] Built target type-utils
[ 94%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__opencog_atomspace_opencog_scm
[ 94%] Built target opencog_go
[ 94%] Compiling opencog/exec.scm
Backtrace:
In system/base/compile.scm:
    59:11 19 (_)
   155:11 18 (_ #<closed: file ccc690>)
   235:18 17 (read-and-compile #<input: opencog/exec.scm 13> #:from _ …)
   183:32 16 (compile-fold (#<procedure compile-tree-il (x e opts)>) …)
In ice-9/boot-9.scm:
   2312:4 15 (save-module-excursion #<procedure dcd900 at language/s…>)
In language/scheme/compile-tree-il.scm:
    31:15 14 (_)
In ice-9/psyntax.scm:
  1235:36 13 (expand-top-sequence ((use-modules (opencog))) _ _ #f c …)
  1182:24 12 (parse _ (("placeholder" placeholder)) ((top) #(# # …)) …)
   285:10 11 (parse _ (("placeholder" placeholder)) (()) _ c&e (# #) #)
In ice-9/boot-9.scm:
  3365:20 10 (process-use-modules _)
   222:17  9 (map1 (((opencog))))
  3366:31  8 (_ ((opencog)))
  2788:17  7 (resolve-interface (opencog) #:select _ #:hide _ # _ # _ …)
  2714:10  6 (_ (opencog) _ _ #:ensure _)
  2982:16  5 (try-module-autoload _ _)
   2312:4  4 (save-module-excursion #<procedure bef120 at ice-9/boot…>)
  3002:22  3 (_)
In unknown file:
           2 (primitive-load-path "opencog" #<procedure dcd400 at ic…>)
           1 (load-extension "EXT_LIB_PATH-NOTFOUND/libsmob" "openco…")
In ice-9/boot-9.scm:
   752:25  0 (dispatch-exception _ _ _)

ice-9/boot-9.scm:752:25: In procedure dispatch-exception:
In procedure dynamic-link: file: "EXT_LIB_PATH-NOTFOUND/libsmob", message: "file not found"
make[2]: *** [opencog/scm/opencog/exec.go] Error 1
make[1]: *** [opencog/scm/CMakeFiles/opencog_exec_go.dir/all] Error 2
make: *** [all] Error 2
The command '/bin/sh -c (mkdir /opencog/atomspace/build; cd /opencog/atomspace/build; 	cmake ..; make -j2; make install)' returned a non-zero code: 2
```

**Comment by mwigzell** [comment]
Hi Matt, the indigo build won't work.
I spent a ton of time updating it in noetic, so that it uses a current
version of ubuntu, newer java version, newer ROS obviously. The docker
files checkout and build the necessary opencog stuff. The dependencies
changed since indigo, and I sorted all that out. I also fixed up the
docker/X11 issues with Blender.
Check out this thread:
https://groups.google.com/g/opencog/c/2fq2zuBEJTs/m/UNHPIBzMAAAJ
The main issue to solve is with updating the Sophia.blend file using the
blender app so that you can keep the python api working AND render the Eva
animations. At that point we could pick up the work and fix the perception
repo so that the ROS commands flow to the blender/ROS node.
Cheers
--Mark

**Comment by Mforrest20** [comment]
Hey Mark,

Are you saying that:
- Even if I make it past building/compiling opencog into the dockerimage, those opencog services won't play nice with ROS once the container is run? 
- Or that you were never able to get the opencog platform running in this context and that this image will never successfully build?

In either case it seems best to let Indigo go and work towards getting eva running with Noetic, especially considering Indigo is well past EOL. To that extent I'm having a hard time getting the Noetic/ros-opencog image to build as well, so I will open a new issue for this and point you towards it.

Leaving this issue open so Linas can find it and weigh in, but from what he has said before I'm effectively attempting necromancy, and that generally doesn't work out well for most parties involved!

**Comment by Mforrest20** [comment]
@mwigzell I've opened #174 to demonstrate the issue I'm having with that ros-opencog image build process.

**Comment by mwigzell** [comment]
Hi Matt, I think that you will not ever be able to run the latest opencog
with "indigo" since opencog needs to build with a later version of Ubuntu
for one, and also I think it has been modernized past the point it will run
with the old versions of java and python.

**Comment by Mforrest20** [comment]
Hey Mark, thats good information (even if its not what I want to hear). I appreciate you doing the leg work ahead of me and having answers for these problems. 

Im going to close this issue as it seems like there's not a solution to this particular use case.

**Comment by mwigzell** [comment]
I'm sure someone of the Blender community could help out, particularly if
offered $$. But as it stands, there is a roadblock to successfully running
"eva-ros" atm.
