### ISSUE TITLE
relationship to circle-ci?

### ISSUE THREAD

**Issue by linas** [opencog/docker#65]
Are these files being used for circle-ci?  Because the atomsapce circle-ci is very unhappy these days.

**Comment by AmeBel** [comment]
yes they are. For atomspace repo circle-ci uses the `opencog/cogutils` image that is autobuilt  @ https://hub.docker.com/r/opencog/cogutils/ when there are changes to this repo,opencog/cogutils, opencog/ocpkg (for dependency changes) repo and when the base ubuntu:14.04 image is updated.

**Comment by linas** [comment]
OK thanks
